github:
    user: wshanks
    repo: zutilo
    token: deploy/github.token
    assets:
    - path: build/zutilo.xpi
      type: application/vnd.zotero.plugin

git_release:
    remote: origin
    branch: release

version_strings:
- path: addon/install.rdf
  pattern: ("version": ")(?P<release>.*)(",)
- path: deploy/update.rdf
  pattern: ("version": )(?P<release>.*)(,)
- path: deploy/update.rdf
  pattern: ("updateLink": "https://github.com/wshanks/Zutilo/releases/download/v)(?P<release>.*)(/zutilo.xpi",)
- path: package.json
  pattern: '^(  "version": ")(?P<release>.*)(",)$'
- path: package-lock.json
  pattern: '^(  "version": ")(?P<release>.*)(",)$'
